### ISSUE TITLE
loudnorm/ebu r128 stats

### ISSUE THREAD

**Issue by bturkus** [amiaopensource/audioqc#5]
hi andrew,

I'm probably revealing my general audio ignorance here, but I was wondering if you'd given any thought to incorporating FFmpeg's loudnorm filter into audioqc. It's hard for me to really tell if it offers audio-related info that astats doesn't already provide, but I think we would be interested in the possibility of an audioqc option that would process files thru loudnorm to give us da LUFS. Have you thought about this at all, and would it be obviously redundant in some way?

thanks!

ben

**Comment by privatezero** [comment]
Hi Ben,
Certainly possible to add some loudness info in! I don't use Loudness in my QC workflow here, as we don't have any hard targets around it for our ingest files, but I see how it could be useful in some workflows, particularly broadcast (and since this project includes NPR via @susiecummings that seems very in scope!) I've been meaning to mess around with some options around phase, so I'll take a look at loudness output as well when I do that!
